//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Newrival.rc
//
#define ID_MENU_1_ACCELERATORS          1
#define BITMAP_1                        1
#define DIALOG_1                        1
#define MENU_1                          1
#define BITMAP_2                        2
#define DIALOG_2                        2
#define MENU_3                          3
#define BITMAP_3                        3
#define DIALOG_3                        3
#define MENU_4                          4
#define DIALOG_4                        4
#define BITMAP_4                        4
#define DIALOG_5                        5
#define BITMAP_5                        5
#define BITMAP_6                        6
#define DIALOG_7                        7
#define BITMAP_7                        7
#define DIALOG_8                        8
#define BITMAP_8                        8
#define BITMAP_9                        9
#define IDC_VISUAL                      10
#define IDC_RADIOBUTTON1                10
#define IDC_PROMOTEQUEEN                10
#define IDC_WHITE_TO_MOVE               10
#define BITMAP_10                       10
#define IDC_REGULAR                     10
#define IDC_TRANSREF                    10
#define IDC_FIXEDLEVEL                  10
#define IDC_FEN                         11
#define IDC_RADIOBUTTON2                11
#define IDC_PROMOTEBISHOP               11
#define IDC_WHITE_KING_MOVED            11
#define BITMAP_11                       11
#define IDC_KINGLET                     11
#define IDC_KILLERS                     11
#define IDC_TIMEPERMOVE                 11
#define IDC_NULLMOVE                    11
#define IDC_FAILHIGHREDUCTIONS			 1823
#define IDC_FENEDIT                     12
#define IDC_PROMOTEROOK                 12
#define IDC_BLACK_KING_MOVED            12
#define BITMAP_12                       12
#define IDC_SHATRANJ                    12
#define IDC_QUIESCE                     12
#define IDC_CHAMPIONSHIP                12
#define IDC_PROMOTEKNIGHT               13
#define IDC_WHITE_ROOK_1_MOVED          13
#define BITMAP_13                       13
#define IDC_SELFTAKE                    13
#define IDC_CONTEMPT                    13
#define IDC_GROUPBOX6                   13
#define IDC_LEVEL                       13
#define IDC_BLACK_ROOK_1_MOVED          14
#define BITMAP_14                       14
#define IDC_MINWIN                      14
#define IDC_GROUPBOX7                   14
#define IDC_USELIBRARY                  14
#define IDC_WHITE_ROOK_8_MOVED          15
#define IDC_PONDER                      15
#define IDC_COMBOBOX1                   15
#define IDC_ADVANCED_BUTTON             15
#define IDC_BLACK_ROOK_8_MOVED          16
#define IDC_EDIT1                       16
#define IDC_BASEINCREMENT               16
#define IDC_HASHBITS                    16
#define IDC_MAXOPENINGPLY               16
#define IDC_PGNEVENT                    16
#define IDC_NULLMOVEPIECES              16
#define IDC_SUITETIME                   16
#define IDC_ENPASSANT                   17
#define IDC_EDIT2                       17
#define IDC_BASEMINUTES                 17
#define IDC_HASHMEGS                    17
#define IDC_MINOPENINGPERCENT           17
#define IDC_SUITEDEPTH                  17
#define IDC_SETUPREGULAR                18
#define IDC_EDIT3                       18
#define IDC_INCREMENT                   18
#define IDC_MINOPENINGRESULTS           18
#define IDC_NULLMOVEREDUCE              18
#define IDC_SUITESTARTDEPTH             18
#define IDC_SETUPKINGLET                19
#define IDC_EDIT4                       19
#define IDC_TIMEHOUR                    19
#define IDC_WINPERCENT                  19
#define IDC_ASPIRATION                  19
#define IDC_SETUPSHATRANJ               20
#define IDC_EDIT5                       20
#define IDC_TIMEMINUTE                  20
#define IDC_WINPERCENTBLACK             20
#define IDC_MAXEXTEND                   20
#define IDC_GROUPBOX1                   21
#define IDC_EDIT6                       21
#define IDC_TIMESECONDS                 21
#define IDC_READHASH                    21
#define IDC_FIFTYMOVES                  22
#define IDC_EDIT7                       22
#define IDC_CHAMPMOVES                  22
#define IDC_WRITEHASH                   22
#define IDC_SETUPSELFTAKE               23
#define IDC_CHAMPHOUR                   23
#define IDC_CHAMPMINUTE                 24
#define IDC_CHAMPSECOND                 25
#define IDC_INFINITE                    26
#define KING1                           101
#define CM_FILE_NEW_GAME                101
#define CM_ITEM                         102
#define QUEEN1                          102
#define CM_ACTION_TAKE_BACK_ONE         102
#define BISHOP1                         103
#define CM_ACTION_REPLAY_ONE            103
#define ROOK1                           104
#define CM_ACTION_TAKE_BACK_ALL         104
#define PAWN1                           105
#define CM_ACTION_REPLAY_ALL            105
#define KNIGHT1                         106
#define CM_FILE_SAVE_GAME               106
#define WHITE1                          107
#define CM_FILE_LOAD_GAME               107
#define BLACK1                          108
#define CM_OPTIONS_PIECE_SLIDE          108
#define CM_OPTIONS_COMPUTER_WHITE       109
#define CM_OPTIONS_COMPUTER_BLACK       110
#define CM_OPTIONS_COMPUTER_PLAY_OPTIONS 111
#define CM_ACTION_PLAY_BEST             112
#define PATHMATE                        112
#define CM_ACTION_STOP_SEARCH           113
#define PATHBISHOP                      113
#define CM_DEFAULT_STYLE_1              114
#define PATHKING                        114
#define CM_OPTIONS_MESSAGES             115
#define PATHKNIGHT                      115
#define CM_OPTIONS_SHOW_ANALYSIS        116
#define PATHM                           116
#define CM_FILE_AUTOSAVE                117
#define CM_OPTIONS_SWITCH_SIDES         118
#define PATHROOK                        118
#define CM_CHANGE_PIECES                119
#define CM_CHANGE_CHESSBOARD            120
#define PATHEQUALS                      120
#define CM_CHANGE_BOX_STYLE             121
#define PATHPLUS                        121
#define CM_CHANGE_WHITE_COLOUR          122
#define IDC_OPENINGBOOK                 122
#define CM_CHANGE_BLACK_COLOUR          123
#define IDB_BITMAP1                     123
#define CM_CHANGE_BACKGROUND_COLOUR     124
#define BISHOP3                         124
#define CM_VCHESS                       125
#define KING3                           125
#define CM_CHANGE_MOVEBOX_STYLE         126
#define KNIGHT3                         126
#define CM_CHANGE_BACKGROUND_STYLE      127
#define PAWN3                           127
#define CM_CHANGE_ANALYSIS_TEXT         128
#define QUEEN3                          128
#define CM_CHANGE_MOVE_TEXT             129
#define ROOK3                           129
#define CM_VSHATRANJ                    130
#define CM_HELP_ABOUT                   131
#define IDI_ICONKING                    131
#define CM_VKINGLET                     132
#define CM_SETUP_BOARD                  133
#define CM_OPTIONS_SAVE_OPTIONS         134
#define CM_SPECIALANALYSE_PGN_FILE      135
#define CM_VSELFTAKE                    136
#define CM_SOLVEFORMATE                 137
#define CM_HELP_CONTENTS                138
#define CM_FILEEXIT                     139
#define IDC_SAVEPGN                     140
#define ANALYSISBOX2                    142
#define IDC_TESTSUITE                   144
#define BISHOP2                         800
#define PAWN2                           801
#define QUEEN2                          802
#define KNIGHT2                         803
#define KING2                           804
#define ROOK2                           805
#define WHITE2                          900
#define WHITE3                          901
#define BLACK2                          902
#define BLACK3                          903
#define SETUP_MENU                      1000
#define ZERO                            1000
#define ONE                             1001
#define TWO                             1002
#define THREE                           1003
#define FOUR                            1004
#define FIVE                            1005
#define SIX                             1006
#define SEVEN                           1007
#define EIGHT                           1008
#define NINE                            1009
#define COLON                           1010
#define IDC_MAXPLYSTATIC                1016
#define IDC_INCLUDEUNKNOWN              1017
#define IDC_OPENINGCOUNT                1018
#define IDC_QUITONERROR                 1019
#define IDC_WHITEPERCENT                1020
#define IDC_MINRESULTS                  1021
#define IDC_BLACKPERCENT                1022
#define IDC_APPENDPGN                   1025
#define IDC_RECAPTUREEXT                1027
#define IDC_CHECKEXT                    1028
#define IDC_PAWNPUSHEXT                 1029
#define IDC_ASPTEXT                     1031
#define IDC_ASPTEXT2                    1032
#define IDC_SINGLEMOVEEXT               1033
#define IDC_USEHISTORY                  1034
#define IDC_CHECK1                      1035
#define IDC_CHECK4                      1038
#define IDC_EXITWHENFOUND               1039
#define IDC_RANDOMORDER                 1040
#define ABOUT                           1099
#define CM_BLACK_PAWN                   1101
#define CM_WHITE_PAWN                   1102
#define CM_WHITE_KNIGHT                 1103
#define CM_WHITE_BISHOP                 1104
#define CM_WHITE_ROOK                   1105
#define CM_WHITE_QUEEN                  1106
#define CM_WHITE_KING                   1107
#define CM_BLACK_KNIGHT                 1108
#define CM_BLACK_BISHOP                 1109
#define CM_BLACK_ROOK                   1110
#define CM_BLACK_QUEEN                  1111
#define CM_BLACK_KING                   1112
#define CM_CLEAR_BOARD                  1113
#define CM_EXIT_SETUP                   1114
#define CM_CLEAR_SQUARE                 1115
#define CM_ABORT_SETUP                  1116
#define SETUP_DIALOG                    1234
#define BACK2                           1999
#define BACK1                           2000
#define PATHNUM1                        2001
#define PATHNUM2                        2002
#define PATHNUM3                        2003
#define PATHNUM4                        2004
#define PATHNUM5                        2005
#define PATHNUM6                        2006
#define PATHNUM7                        2007
#define PATHNUM8                        2008
#define PATHNUMA                        2011
#define PATHNUMB                        2012
#define PATHNUMC                        2013
#define PATHNUMD                        2014
#define PATHNUME                        2015
#define PATHNUMF                        2016
#define PATHNUMG                        2017
#define PATHNUMH                        2018
#define PATHNUM0                        2020
#define PATHNUM9                        2029
#define PATHCROSS                       2030
#define PATHDASH                        2031
#define PATHDOT                         2032
#define ANALYSISBOX                     3000
#define MOVEBOX                         3001
#define IDC_SETUPMETHOD                 3441
#define COMPUTER_OPTIONS_DIALOG         5000
#define ADVANCED_COMPUTER_OPTIONS_DIALOG 5001
#define ADVANCED_COMPUTER_PLAY_DIALOG   5001
#define NEWGAMEDIALOG                   5005
#define PROMOTE_DIALOG                  5176
#define PATHQUEEN                       28437
#define CM_CREATEOPENINGBOOK            40001
#define CM_INVERT_BOARD						 40002
#define CM_FILE_SAVE_PGN                40003
#define CM_FILE_SAVE_POSITION           40004
#define CM_LOGS_VERBOSE                 40005
#define CM_LOGS_TIMINGS                 40006
#define CM_LOGS_PV                      40007
#define CM_RESIGN                       40008
#define CM_OFFERDRAW                    40009
#define CM_FLAG                         40010
#define CM_LOADPOSITION                 40011
#define CM_DEFAULT_OPTIONS              40013
#define CM_TESTSUITE                    40015
#define IDC_HASHSIZE                    -1
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         40016
#define _APS_NEXT_CONTROL_VALUE         1041
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
